config/routes.rb
Rails.application.routes.draw do
  get "/" => "top#index"

  resources "tops", only: :index
  resources "flowers", only: :index
  resources "tag_images", only: :index
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/flower_searchable.rb
module FlowerSearchable
  # ActiveSupportクラスを継承
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    index_name "flower_#{Rails.env}"

    # Set up index configuration and mapping
    settings do
      mappings dynamic: 'false' do
        indexes :name, type: 'text', analyzer: "kuromoji"

        indexes :flower_tags, type: :nested do
          indexes :tag, type: 'text', analyzer: "kuromoji"
          indexes :red, type: 'text', analyzer: "kuromoji"
          indexes :blue, type: 'text', analyzer: "kuromoji"
          indexes :green, type: 'text', analyzer: "kuromoji"

        end
      end
    end

    def as_indexed_json(options={})
      as_json(only: %i(id name), include: {only: %i(tag red blue green)})
      # flower_attrs = {
      #   id: self.id,
      #   name: self.name
      # }
      # flower_attrs[:flower_tags] = self.flower_tag.map do |fl|
      #   {
      #     tag: fl.tag,
      #     red: fl.red,
      #     blue: fl.blue,
      #     green: fl.green
      #   }
      # end
      # flower_attrs.as_json
    end

    def self.search query
      search_definition = Elasticsearch::DSL::Search.search({
        match_all: {
          query: query,
          fuzziness: "AUTO",
          fields: ['name', 'flower_tags.tag', 'flower_tags.red', 'flower_tags.green', 'flower_tags.blue']
        }
      })
    end
  end
end

app/models/concerns/flower_tag_searchable.rb
module FlowerTagSearchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    # Set up index configuration and mapping
    mapping do
      indexes :id, type: "integer", index: "not_analyzed"
      indexes :tag, type: "string", analyzer: "kuromoji_analyzer",

      _source: {enabled: true},
      _all: {enabled: true, analyzer: "kuromoji_analyzer"} do
        indexes :id, type: "integer", index: "not_analyzed"
        indexes :tag, type: "string", analyzer: "kuromoji_analyzer"
      end
    end

    index_name "flower_#{Rails.env}"

    def as_indexed_json(options={})
      as_json(only: %i(id name))
      # flower_attrs = {
      #   id: self.id,
      #   tag: self.tag
      # }
      # flower_attrs.as_json
    end

    def self.search
      search_definition = Elasticsearch::DSL::Search.search({
        match: {
          "flower_tag.keyword": self,
          fuzziness: "AUTO"
        }
      })
    end
  end

  # module ClassMethods
  class_methods do
    def create_index!(options={})
      client = __elasticsearch__.client
      client.indices.delete index: self.index_name rescue nil
      client.indices.create(index: self.index_name,
                            body: {
                              settings: self.settings.to_hash,
                              mappings: self.mappings.to_hash
                            })
    end
  end
end

app/models/flower.rb
require 'elasticsearch/model'
class Flower < ApplicationRecord
  include Elasticsearch::Model
  include FlowerSearchable

  has_many :flower_tag
end

app/models/flower_tag.rb
require 'elasticsearch/model'
class FlowerTag < ApplicationRecord
  include Elasticsearch::Model
  include FlowerTagSearchable

  belongs_to :flower

  private
  def flower_tag_params
    params.require(:flower_tag).permit(:flower_id, :tag)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  def index
    if params[:search]
      @flowers_results = Flower.__elasticsearch__.search("*#{params[:search]}*")
      @ids = @flowers_results.map{|f| f.id}
      @flowers = Flower.where(id: @ids)
    else
      @flowers = Flower.all
    end
  end

  def create
    @flower = Flower.new(flower_params)
  end

  def update

  end

  private
  def flower_params
    params.require(:flower).permit(:name, :img)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def embedded_svg filename, options={}
   file = File.read(Rails.root.join('app', 'assets', 'images', filename))
   doc = Nokogiri::HTML::DocumentFragment.parse file
   svg = doc.at_css 'svg'
   if options[:class].present?
     svg['class'] = options[:class]
   end
   doc.to_html.html_safe
 end
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/flowers/index.html.slim
.box.-right
  h1.title.-fl-name
    | 花見図鑑
  /p
    | Find me in app/views/flowers/index.html.erb
  = form_tag flowers_path, :method => :get do
    = text_field_tag :search, params[:search], class: "form__text"
    = submit_tag "検索", :name=> nil, class: "form__input"
  end
  div style="display: flex;flex-direction: row;"
    div style="display: flex;flex-direction: column;"
      - @flowers.each do |fl|
        ul.container
          li style="flex: 1;"
            = image_tag "https://www.shuminoengei.jp/#{fl.img}"
          li.title.-fl-name style="flex: 1;"
            = fl.name
          li style="display: flex;"
            - fl.flower_tag.each do |tag|
              .pallete__small style="background: ##{tag.tag};"
                .color-description = "#{tag.tag}"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Floap
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    script crossorigin="anonymous" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" src="https://code.jquery.com/jquery-2.2.4.min.js" 
  body
    .container
      = render "top/left_column"
      = yield

app/views/tag_images/index.slim
- @tag_images.each do |tag|
  style background-color="#{tag}"

app/views/top/_left_column.slim
.box__top.-left
  = embedded_svg "logo.svg", class: ""
  ul.menu__fade.border__preset
    li
      = link_to "top", "/"
    li
      = link_to "about", ""
    li
      = link_to "search", flowers_path
    li
      = link_to "pict", ""
    li
      = link_to do
        = embedded_svg "GitHub-Mark-64px.svg", class: "title -github"

app/views/top/_right_column.slim
.box.-right
  = image_tag "IMG_1221.JPG", class: "img -fade-top"
  = image_tag "IMG_12.JPG", class: "img -fade-middle"
  = image_tag "IMG_1295.JPG", class: "img -fade-bottom"
  = image_tag "IMG_1292.JPG", class: "img -fade-middle"
  = image_tag "IMG_1251.JPG", class: "img -fade-bottom"

app/views/top/index.html.slim
= render "top/right_column"

app/views/top/index.js.erb
<%%>